version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0  
    commands:
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
  build:
    commands:
      - cd EmergencySystem/Web
      - dotnet eb package
artifacts:
  files:
    - ./EmergencySystem/Web/bin/Release/net6.0/*
  discard-paths: yes